---
# handlers file for setup-apachea
- name : Start httpd service
  service :
    name : httpd
    state : started
- name : restart httpd service 
  service :
    name : httpd
    state : restarted

